const quotes = [ "I don't think that you have any insight whatsoever into your capacity for good until you have some well-developed insight into your capacity for evil.",
"When you have something to say, silence is a lie.", 
"You can only find out what you actually believe (rather than what you think you believe) by watching how you act. You simply don’t know what you believe, before that. You are too complex to understand yourself",
"If you can't understand why someone is doing something, look at the consequences of their actions, whatever they might be, and then infer the motivations from their consequences.",
"If you don't say what you think then you kill your unborn self",
"And if you think tough men are dangerous, wait until you see what weak men are capable of.",
"If you fulfill your obligations everyday you don't need to worry about the future",
"It took untold generations to get you where you are. A little gratitude might be in order. If you're going to insist on bending the world to your way, you better have your reasons",
"Life is suffering Love is the desire to see unnecessary suffering ameliorated Truth is the handmaiden of love Dialogue is the pathway to truth Humility is recognition of personal insufficiency and the willingness to learn To learn is to die voluntarily and be born again, in great ways and small So speech must be untrammeled So that dialogue can take place So that we can all humbly learn So that truth can serve love So that suffering can be ameliorated So that we can all stumble forward to the Kingdom of God",
"Women select men. That makes them nature, because nature is what selects. And you can say 'Well it's only symbolic that women are nature', it's like no, it's not just symbolic. The woman is the gatekeeper to reproductive success. And you can't get more like nature than that, in fact it's the very definition of nature",
"No tree can grow to Heaven,” adds the ever-terrifying Carl Gustav Jung, psychoanalyst extraordinaire, “unless its roots reach down to Hell",
"Intolerance of others’ views (no matter how ignorant or incoherent they may be) is not simply wrong; in a world where there is no right or wrong, it is worse: it is a sign you are embarrassingly unsophisticated or, possibly, dangerous",
"To suffer terribly and to know yourself as the cause: that is Hell",
"Don’t underestimate the power of vision and direction. These are irresistible forces, able to transform what might appear to be unconquerable obstacles into traversable pathways and expanding opportunities. Strengthen the individual. Start with yourself. Take care with yourself. Define who you are. Refine your personality. Choose your destination and articulate your Being. As the great nineteenth-century German philosopher Friedrich Nietzsche so brilliantly noted, “He whose life has a why can bear almost any how",
"So, attend carefully to your posture. Quit drooping and hunching around. Speak your mind. Put your desires forward, as if you had a right to them—at least the same right as others. Walk tall and gaze forthrightly ahead. Dare to be dangerous. Encourage the serotonin to flow plentifully through the neural pathways desperate for its calming influence",
"The purpose of life, as far as I can tell… is to find a mode of being that’s so meaningful that the fact that life is suffering is no longer relevant",
"Ideologies are substitutes for true knowledge, and ideologues are always dangerous when they come to power, because a simple-minded I-know-it-all approach is no match for the complexity of existence",
"Perhaps you are overvaluing what you don’t have and undervaluing what you do",
"RULE 4 COMPARE YOURSELF TO WHO YOU WERE YESTERDAY, NOT TO WHO SOMEONE ELSE IS TODAY",
"You must determine where you are going in your life, because you cannot get there unless you move in that direction. Random wandering will not move you forward. It will instead disappoint and frustrate you and make you anxious and unhappy and hard to get along with (and then resentful, and then vengeful, and then worse)",
"If you are not willing to be a fool, you can't become a master",
"In the West, we have been withdrawing from our tradition-, religion- and even nation-centred cultures, partly to decrease the danger of group conflict. But we are increasingly falling prey to the desperation of meaninglessness, and that is no improvement at all",
"In order to be able to think, you have to risk being offensive",
"If you have a comprehensive explanation for everything then it decreases uncertainty and anxiety and reduces your cognitive load. And if you can use that simplifying algorithm to put yourself on the side of moral virtue then you’re constantly a good person with a minimum of effort",
"You cannot be protected from the things that frighten you and hurt you, but if you identify with the part of your being that is responsible for transformation, then you aare always the equal, or more than the equal of the things that frighten you",
"The better ambitions have to do with the development of character and ability, rather than status and power. Status you can lose. You carry character with you wherever you go, and it allows you to prevail against adversity",
"You don't get to choose not to pay a price, you only get to choose which price you pay",
"Of course, my socialist colleagues and I weren’t out to hurt anyone – quite the reverse. We were out to improve things – but we were going to start with other people. I came to see the temptation in this logic, the obvious flaw, the danger – but could also see that it did not exclusively characterize socialism. Anyone who was out to change the world by changing others was to be regarded with suspicion. The temptations of such a position were too great to be resisted",
"Every bit of learning is a little death. Every bit of new information challenges a previous conception, forcing it to dissolve into chaos before it can be reborn as something better. Sometimes such deaths virtually destroy us",
"So, listen, to yourself and to those with whom you are speaking. Your wisdom then consists not of the knowledge you already have, but the continual search for knowledge, which is the highest form of wisdom",
"The successful among us delay gratification. The successful among us bargain with the future",
"Nietzsche said that a man’s worth was determined by how much truth he could tolerate",
"Always place your becoming above your current being",
"There are some games you don't get to play unless you are all in",
"People organize their brains with conversation. If they don't have anyone to tell their story to, they lose their minds. Like hoarders, they cannot unclutter themselves",
"It is my firm belief that the best way to fix the world—a handyman’s dream, if ever there was one—is to fix yourself",
"If your life is not what it could be, try telling the truth. If you cling desperately to an ideology, or wallow in nihilism, try telling the truth. If you feel weak and rejected, and desperate, and confused, try telling the truth. In Paradise, everyone speaks the truth. That is what makes it Paradise. Tell the truth. Or, at least, don’t lie",
"Stop saying those things that make you weak and ashamed. Say only those things that make you strong. Do only those things that you could speak of with honour",
"We require routine and tradition. That’s order. Order can become excessive, and that’s not good, but chaos can swamp us, so we drown— and that is also not good. We need to stay on the straight and narrow path",
"The secret to your existence is right in front of you. It manifests itself as all those things you know you should do, but are avoiding",
"Don’t ever underestimate the destructive power of sins of omission",
"Consciousness is a mystery that faces the mystery of potential and transforms it into actuality. We do that with every choice we make. Our choices determine the destiny of the world. By making a choice, you alter the structure of reality",
"We believe that in reducing the scope and importance of our errors, we are properly humble; in truth, we are merely unwilling to bear the weight of our true responsibility",
"Don’t use language instrumentally",
"What you aim at determines what you see",
"If you betray yourself, if you say untrue things, if you act out a lie, you weaken your character",
"Worthlessness is the default condition",
"Sometimes it seems the only people willing to give advice in a relativistic society are those with the least to offer",
"If a child has not been taught to behave properly by the age of four, it will forever be difficult for him or her to make friends",
"It's a luxury to pursue what makes you happy; it's a moral obligation to pursue what you find meaningful",
"It’s appropriate and praiseworthy to associate with people whose lives would be improved if they saw your life improve",
"Mark Twain once said, “It’s not what we don’t know that gets us in trouble. It’s what we know for sure that just ain’t so",
"Dreams shed light on the dim places where reason itself has yet to voyage",
"Question for parents: do you want to make your children safe, or strong?",
"It is far better to render Beings in your care competent than to protect them",
"There’s some real utility in gratitude. It’s also good protection against the dangers of victimhood and resentment",
"When the aristocracy catches a cold, as it is said, the working class dies of pneumonia",
"you should never sacrifice what you could be for what you are",
"It is better, proverbially, to rule your own spirit than to rule a city",
"One of the problems with being relatively wealthy if you are a parent is that you cannot provide your children with necessity",
"Beauty shames the ugly. Strength shames the weak. Death shames the living - and the Ideal shames us all",
"We cannot navigate, without something to aim at and, while we are in this world, we must always navigate",
"We require rules, standards, values— alone and together. We’re pack animals, beasts of burden. We must bear a load, to justify our miserable existence",
"But the story of the golden calf also reminds us that without rules we quickly become slaves to our passions—and there’s nothing freeing about that",
"The first: limit the rules. The second: Use the least force necessary to enforce those rules",
"There are so many ways that things can fall apart, or fail to work altogether, and it is always wounded people who are holding it together",
"alongside our wish to be free of rules, we all search for structure",
"It isn’t precisely that people will fight for what they believe. They will fight, instead, to maintain the match between what they believe, what they expect, and what they desire",
"Life without law remains chaotic, effectively intolerable. Life that is pure law becomes sterile, equally unbearable. The domination of chaos or sterility equally breeds murderous resentment and hatred",
"Much of happiness is hope, no matter how deep the underworld in which that hope was conceived",
"Perhaps happiness is always to be found in the journey uphill, and not in the fleeting sense of satisfaction awaiting at the next peak. Much of happiness is hope",
"the soul of the individual eternally hungers for the heroism of genuine Being, and that the willingness to take on that responsibility is identical to the decision to live a meaningful life",
"Kindness is the excuse that social justice warriors use when they want to exercise control over what other people think and say",
"There’s a worthy and noble ambition: strength in the face of adversity. That is very different from the wish for a life free of trouble",
"There is very little difference between the capacity for mayhem and destruction, integrated, and strength of character. This is one of the most difficult lessons of life",
"what can be truly loved about a person is inseparable from their limitations",
"It is not virtuous to be victimized by a bully, even if that bully is oneself",
"Life is indistinguishable from effortful maintenance",
"We outsource the problem of sanity. People remain mentally healthy not merely because of the integrity of their own minds, but because they are constantly being reminded how to think, act, and speak by those around them",
"90 percent of communication occurs using just 500 words",
"That which you most need to find will be found where you least wish to look",
"Treat yourself like you would someone you're responsible for helping",
"Lobsters have more in common with you than you might think",
"Territory matters, and there is little difference between territorial rights and social status. It is often a matter of life and death",
"we may not exactly be God, but we’re not exactly nothing, either",
"The only time no ever means no in the absence of violence is when it is uttered by one civilized person to another",
"Aristotle defined the virtues simply as the ways of behaving that are most conducive to happiness in life.",
"But we can aim too high. Or too low. Or too chaotically. So we fail and live in disappointment, even when we appear to others to be living well",
"It is instead the realization that the tragic irrationalities of life must be counterbalanced by an equally irrational commitment to the essential goodness of Being",
"A certain amount of creativity and rebellion must be tolerated - or welcomed, depending on your point of view - to maintain the process of regeneration. Every rule was once a creative act, breaking other rules",
"True thinking is rare—just like true listening",
"The light that you discover in your life is proportionate to the amount of the darkness you are willing to forthrightly confront",
"What shall I do when my enemy succeeds? Aim a little higher and be grateful for the lesson",
"Truth reduces the terrible complexity of a man to the simplicity of his word",
"Humility: It is better to presume ignorance and invite learning than to assume sufficient knowledge and risk the consequent blindness",
"Your inaction, inertia and cynicism removes from the world that part of you that could learn to quell suffering and make peace",
"but damaged machinery will continue to malfunction if its problems are neither diagnosed nor fixed",
"You remember the past not so that it is “accurately recorded,” to say it again, but so that you are prepared for the future",
"You're not perfect just the way you are. You could be better!",
"In a crisis, the inevitable suffering that life entails can rapidly make a mockery of the idea that happiness is the proper pursuit of the individual"
];